export const JWT_ACCESS_SECRET = `JWT_ACCESS_SECRET`;
export const JWT_ACCESS_EXPIRES = `JWT_ACCESS_EXPIRES`;

export const JWT_REFRESH_SECRET = `JWT_REFRESH_SECRET`;
export const JWT_REFRESH_EXPIRES = `JWT_REFRESH_EXPIRES`;
